name: Run prometheus unit tests
on:
  pull_request:
    paths:
      - 'config/monitoring/prometheus/**'
      - 'tests/prometheus_unit_tests/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Promtool
      run: |
        sudo apt-get update && sudo apt-get install -y prometheus
    - name: Run prometheus-unit-tests
      run : make test-alerts
